url: "https://rosewills.github.io"			# Hostname & protocol of site (e.g. http://example.com)
baseurl: "/rw-jekyll-theme"							# Subpath of site (e.g. /blog)
title: "RW Jekyll Theme"				# Name of site (e.g. ACME Corp.)
description: "A Jekyll theme for writers."
email: rosiepyw@gmail.com
name: Rose Wills

# Graphics
cover: ""
acover: ""	# /assets/art/windowsill.png
bcover: ""
logo:

# Posts
future: false
permalink: /:year/:month/:day/:title.html

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2

# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
pagination:											# Configuration for the Jekyll 3 Pagination Gem (the values here represent the defaults if nothing is set)
  enabled: true									# Site-wide kill switch, disabled here it doesn't run at all 
  debug: false									# Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  collection: 'posts'						# The default document collection to paginate if nothing is specified ('posts' is default)
  per_page: 10										# How many objects per paginated page, used to be `paginate` (default: 0, means all)
  limit: 0											# Limit how many pagenated pages to create (default: 0, means all)
  title: ':title - page :num'		# [optional] the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  sort_field: 'date'						# [optional] defines the field that the posts should be sorted on (omit to default to 'date')
  sort_reverse: true						# [optional] sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  category: 'posts'							# [optional] the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  tag: ''												# [optional] the default tag to use, omit to disable
  locale: '' 										# [optional] the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code)
  extension: html								# [optional] the default file extension for generated pages (e.g html, json, xml). Internally this is set to html by default.
  indexpage: 'index'						# [optional] the default name of the index file for generated pages (e.g. 'index.html') without file extension
  trail:												# [optional] controls how the pagination trail for the paginated pages look like. omit or set both before and after to zero to disable.
    before: 2
    after: 2
  permalink: '/page/:num/'			# The permalink structure for the paginated pages (this can be any level deep)
                                    # permalink: '/page/:num/'      # Pages are index.html inside this folder (default)
                                    # permalink: '/page/:num.html'  # Pages are simple html files
                                    # permalink: '/page/:num'       # Pages are html files, linked jekyll extensionless permalink style.

# Exclude
exclude:							# Ignore these directories when generating the site
  - "/vendor/"
  - "/template/"
  - ".obsidian/"
  - "ofiles/"
