menu:
- {name: "blog", url: "/blog"}
- {name: "about", url: "/about"}
- {name: "archive", url: "/archive"}

social:
- {site: "Linkedin", user: "rmvwills", icon: "linkedin", link: "https://linkedin.com/in/rmvwills/"}
- {site: "Github", user: "rosewills", icon: "github", link: "https://github.com/rosewills"}
- {site: "Instagram", user: "suddenlyrose", icon: "instagram", link: "https://instagram.com/suddenlyrose"}
- {site: "Twitter", user: "rosevwills", icon: "twitter", link: "https://twitter.com/rosevwills"}
